name: Pull Request
run-name: Pull Request for Python
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'main'

jobs:
  lint:
    name: Ruff lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Ruff lint
        uses: chartboost/ruff-action@v1

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rye
        uses: eifinger/setup-rye@v1

      - name: Rye sync
        run: rye sync --no-lock
