name: Pull Request
run-name: Pull Request for Python
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: Set up Python
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: '3.8'

      - name: Set up rye
        uses: eifinger/setup-rye@v1

      - name: Rye sync
        run: |
          rye sync

      - name: Ruff lint
        uses: chartboost/ruff-action@v1
